name: Test and Build

on: [pull_request, push]

env:
  FORCE_COLOR: 1
  node_version: 'lts/*'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node_version }}
    - run: npm i
    - run: npm test --color=always
    - run: npm run build
    - name: Archive lockfile
      uses: actions/upload-artifact@v4
      with:
        name: pacakge-lock-${{ matrix.os }}.json
        path: package-lock.json


  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.head_ref, 'dependabot/github_actions') }}
        with:
          github-token: ${{secrets.github_token}}
